export const COUNTRIES = [
  { code: 'AR', name: 'Argentina',          flag: '🇦🇷', lang: 'es' },
  { code: 'BO', name: 'Bolivia',             flag: '🇧🇴', lang: 'es' },
  { code: 'BR', name: 'Brasil',              flag: '🇧🇷', lang: 'pt' },
  { code: 'CA', name: 'Canadá',             flag: '🇨🇦', lang: 'en' },
  { code: 'CL', name: 'Chile',              flag: '🇨🇱', lang: 'es' },
  { code: 'CO', name: 'Colombia',            flag: '🇨🇴', lang: 'es' },
  { code: 'CR', name: 'Costa Rica',          flag: '🇨🇷', lang: 'es' },
  { code: 'CU', name: 'Cuba',               flag: '🇨🇺', lang: 'es' },
  { code: 'DO', name: 'Rep. Dominicana',     flag: '🇩🇴', lang: 'es' },
  { code: 'EC', name: 'Ecuador',             flag: '🇪🇨', lang: 'es' },
  { code: 'ES', name: 'España',             flag: '🇪🇸', lang: 'es' },
  { code: 'GT', name: 'Guatemala',           flag: '🇬🇹', lang: 'es' },
  { code: 'HN', name: 'Honduras',            flag: '🇭🇳', lang: 'es' },
  { code: 'MX', name: 'México',             flag: '🇲🇽', lang: 'es' },
  { code: 'NI', name: 'Nicaragua',           flag: '🇳🇮', lang: 'es' },
  { code: 'PA', name: 'Panamá',            flag: '🇵🇦', lang: 'es' },
  { code: 'PE', name: 'Perú',              flag: '🇵🇪', lang: 'es' },
  { code: 'PR', name: 'Puerto Rico',         flag: '🇵🇷', lang: 'es' },
  { code: 'PY', name: 'Paraguay',            flag: '🇵🇾', lang: 'es' },
  { code: 'SV', name: 'El Salvador',         flag: '🇸🇻', lang: 'es' },
  { code: 'UY', name: 'Uruguay',             flag: '🇺🇾', lang: 'es' },
  { code: 'VE', name: 'Venezuela',           flag: '🇻🇪', lang: 'es' },
  { code: 'US', name: 'Estados Unidos',      flag: '🇺🇸', lang: 'en' },
  { code: 'GB', name: 'Reino Unido',         flag: '🇬🇧', lang: 'en' },
  { code: 'AU', name: 'Australia',           flag: '🇦🇺', lang: 'en' },
  { code: 'PT', name: 'Portugal',            flag: '🇵🇹', lang: 'pt' },
  { code: 'FR', name: 'Francia',             flag: '🇫🇷', lang: 'fr' },
  { code: 'DE', name: 'Alemania',            flag: '🇩🇪', lang: 'de' },
  { code: 'IT', name: 'Italia',              flag: '🇮🇹', lang: 'it' },
  { code: 'RU', name: 'Rusia',              flag: '🇷🇺', lang: 'ru' },
  { code: 'JP', name: 'Japón',             flag: '🇯🇵', lang: 'ja' },
  { code: 'KR', name: 'Corea del Sur',       flag: '🇰🇷', lang: 'ko' },
  { code: 'CN', name: 'China',              flag: '🇨🇳', lang: 'zh' },
  { code: 'IN', name: 'India',              flag: '🇮🇳', lang: 'hi' },
  { code: 'TR', name: 'Turquía',           flag: '🇹🇷', lang: 'tr' },
  { code: 'SA', name: 'Arabia Saudita',      flag: '🇸🇦', lang: 'ar' },
  { code: 'PH', name: 'Filipinas',           flag: '🇵🇭', lang: 'en' },
  { code: 'NG', name: 'Nigeria',             flag: '🇳🇬', lang: 'en' },
  { code: 'ZA', name: 'Sudáfrica',         flag: '🇿🇦', lang: 'en' },
];

export const LANGUAGES = [
  { code: 'es', name: 'Español' },
  { code: 'en', name: 'English' },
  { code: 'pt', name: 'Português' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'ru', name: 'Русский' },
  { code: 'ja', name: '日本語' },
  { code: 'zh', name: '中文' },
  { code: 'ar', name: 'العربية' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'ko', name: '한국어' },
  { code: 'tr', name: 'Türkçe' },
];

export const countryByCode = (code) => COUNTRIES.find(c => c.code === code);
export const languageByCode = (code) => LANGUAGES.find(l => l.code === code);
