export const COUNTRIES = [
  // ── Latinoamérica ──
  { code: 'AR', name: 'Argentina',           flag: '🇦🇷', lang: 'es' },
  { code: 'BO', name: 'Bolivia',             flag: '🇧🇴', lang: 'es' },
  { code: 'BR', name: 'Brasil',              flag: '🇧🇷', lang: 'pt' },
  { code: 'CL', name: 'Chile',               flag: '🇨🇱', lang: 'es' },
  { code: 'CO', name: 'Colombia',            flag: '🇨🇴', lang: 'es' },
  { code: 'CR', name: 'Costa Rica',          flag: '🇨🇷', lang: 'es' },
  { code: 'CU', name: 'Cuba',                flag: '🇨🇺', lang: 'es' },
  { code: 'DO', name: 'Rep. Dominicana',     flag: '🇩🇴', lang: 'es' },
  { code: 'EC', name: 'Ecuador',             flag: '🇪🇨', lang: 'es' },
  { code: 'GT', name: 'Guatemala',           flag: '🇬🇹', lang: 'es' },
  { code: 'HN', name: 'Honduras',            flag: '🇭🇳', lang: 'es' },
  { code: 'MX', name: 'México',              flag: '🇲🇽', lang: 'es' },
  { code: 'NI', name: 'Nicaragua',           flag: '🇳🇮', lang: 'es' },
  { code: 'PA', name: 'Panamá',              flag: '🇵🇦', lang: 'es' },
  { code: 'PE', name: 'Perú',                flag: '🇵🇪', lang: 'es' },
  { code: 'PR', name: 'Puerto Rico',         flag: '🇵🇷', lang: 'es' },
  { code: 'PY', name: 'Paraguay',            flag: '🇵🇾', lang: 'es' },
  { code: 'SV', name: 'El Salvador',         flag: '🇸🇻', lang: 'es' },
  { code: 'UY', name: 'Uruguay',             flag: '🇺🇾', lang: 'es' },
  { code: 'VE', name: 'Venezuela',           flag: '🇻🇪', lang: 'es' },

  // ── Norteamérica ──
  { code: 'CA', name: 'Canadá',              flag: '🇨🇦', lang: 'en' },
  { code: 'US', name: 'Estados Unidos',      flag: '🇺🇸', lang: 'en' },

  // ── Europa ──
  { code: 'AT', name: 'Austria',             flag: '🇦🇹', lang: 'de' },
  { code: 'BE', name: 'Bélgica',             flag: '🇧🇪', lang: 'fr' },
  { code: 'BG', name: 'Bulgaria',            flag: '🇧🇬', lang: 'ru' },
  { code: 'CH', name: 'Suiza',               flag: '🇨🇭', lang: 'de' },
  { code: 'CZ', name: 'Chequia',             flag: '🇨🇿', lang: 'en' },
  { code: 'DE', name: 'Alemania',            flag: '🇩🇪', lang: 'de' },
  { code: 'DK', name: 'Dinamarca',           flag: '🇩🇰', lang: 'en' },
  { code: 'ES', name: 'España',              flag: '🇪🇸', lang: 'es' },
  { code: 'FI', name: 'Finlandia',           flag: '🇫🇮', lang: 'en' },
  { code: 'FR', name: 'Francia',             flag: '🇫🇷', lang: 'fr' },
  { code: 'GB', name: 'Reino Unido',         flag: '🇬🇧', lang: 'en' },
  { code: 'GR', name: 'Grecia',              flag: '🇬🇷', lang: 'en' },
  { code: 'HU', name: 'Hungría',             flag: '🇭🇺', lang: 'en' },
  { code: 'IE', name: 'Irlanda',             flag: '🇮🇪', lang: 'en' },
  { code: 'IT', name: 'Italia',              flag: '🇮🇹', lang: 'it' },
  { code: 'NL', name: 'Países Bajos',        flag: '🇳🇱', lang: 'en' },
  { code: 'NO', name: 'Noruega',             flag: '🇳🇴', lang: 'en' },
  { code: 'PL', name: 'Polonia',             flag: '🇵🇱', lang: 'en' },
  { code: 'PT', name: 'Portugal',            flag: '🇵🇹', lang: 'pt' },
  { code: 'RO', name: 'Rumanía',             flag: '🇷🇴', lang: 'en' },
  { code: 'RS', name: 'Serbia',              flag: '🇷🇸', lang: 'en' },
  { code: 'RU', name: 'Rusia',               flag: '🇷🇺', lang: 'ru' },
  { code: 'SE', name: 'Suecia',              flag: '🇸🇪', lang: 'en' },
  { code: 'UA', name: 'Ucrania',             flag: '🇺🇦', lang: 'ru' },

  // ── Asia ──
  { code: 'BD', name: 'Bangladés',           flag: '🇧🇩', lang: 'hi' },
  { code: 'CN', name: 'China',               flag: '🇨🇳', lang: 'zh' },
  { code: 'HK', name: 'Hong Kong',           flag: '🇭🇰', lang: 'zh' },
  { code: 'ID', name: 'Indonesia',           flag: '🇮🇩', lang: 'en' },
  { code: 'IN', name: 'India',               flag: '🇮🇳', lang: 'hi' },
  { code: 'JP', name: 'Japón',               flag: '🇯🇵', lang: 'ja' },
  { code: 'KH', name: 'Camboya',             flag: '🇰🇭', lang: 'en' },
  { code: 'KR', name: 'Corea del Sur',       flag: '🇰🇷', lang: 'ko' },
  { code: 'LK', name: 'Sri Lanka',           flag: '🇱🇰', lang: 'en' },
  { code: 'MM', name: 'Birmania',            flag: '🇲🇲', lang: 'en' },
  { code: 'MY', name: 'Malasia',             flag: '🇲🇾', lang: 'en' },
  { code: 'NP', name: 'Nepal',               flag: '🇳🇵', lang: 'hi' },
  { code: 'PH', name: 'Filipinas',           flag: '🇵🇭', lang: 'en' },
  { code: 'PK', name: 'Pakistán',            flag: '🇵🇰', lang: 'hi' },
  { code: 'SG', name: 'Singapur',            flag: '🇸🇬', lang: 'en' },
  { code: 'TH', name: 'Tailandia',           flag: '🇹🇭', lang: 'en' },
  { code: 'TW', name: 'Taiwán',              flag: '🇹🇼', lang: 'zh' },
  { code: 'VN', name: 'Vietnam',             flag: '🇻🇳', lang: 'en' },

  // ── Medio Oriente ──
  { code: 'AE', name: 'Emiratos Árabes',     flag: '🇦🇪', lang: 'ar' },
  { code: 'EG', name: 'Egipto',              flag: '🇪🇬', lang: 'ar' },
  { code: 'IL', name: 'Israel',              flag: '🇮🇱', lang: 'en' },
  { code: 'IR', name: 'Irán',                flag: '🇮🇷', lang: 'ar' },
  { code: 'IQ', name: 'Irak',                flag: '🇮🇶', lang: 'ar' },
  { code: 'JO', name: 'Jordania',            flag: '🇯🇴', lang: 'ar' },
  { code: 'KW', name: 'Kuwait',              flag: '🇰🇼', lang: 'ar' },
  { code: 'LB', name: 'Líbano',              flag: '🇱🇧', lang: 'ar' },
  { code: 'OM', name: 'Omán',                flag: '🇴🇲', lang: 'ar' },
  { code: 'QA', name: 'Catar',               flag: '🇶🇦', lang: 'ar' },
  { code: 'SA', name: 'Arabia Saudita',      flag: '🇸🇦', lang: 'ar' },
  { code: 'TR', name: 'Turquía',             flag: '🇹🇷', lang: 'tr' },

  // ── África ──
  { code: 'AO', name: 'Angola',              flag: '🇦🇴', lang: 'pt' },
  { code: 'CI', name: 'Costa de Marfil',     flag: '🇨🇮', lang: 'fr' },
  { code: 'CM', name: 'Camerún',             flag: '🇨🇲', lang: 'fr' },
  { code: 'DZ', name: 'Argelia',             flag: '🇩🇿', lang: 'ar' },
  { code: 'ET', name: 'Etiopía',             flag: '🇪🇹', lang: 'en' },
  { code: 'GH', name: 'Ghana',               flag: '🇬🇭', lang: 'en' },
  { code: 'KE', name: 'Kenia',               flag: '🇰🇪', lang: 'en' },
  { code: 'MA', name: 'Marruecos',           flag: '🇲🇦', lang: 'ar' },
  { code: 'MZ', name: 'Mozambique',          flag: '🇲🇿', lang: 'pt' },
  { code: 'NG', name: 'Nigeria',             flag: '🇳🇬', lang: 'en' },
  { code: 'SN', name: 'Senegal',             flag: '🇸🇳', lang: 'fr' },
  { code: 'TN', name: 'Túnez',               flag: '🇹🇳', lang: 'ar' },
  { code: 'UG', name: 'Uganda',              flag: '🇺🇬', lang: 'en' },
  { code: 'ZA', name: 'Sudáfrica',           flag: '🇿🇦', lang: 'en' },
  { code: 'ZW', name: 'Zimbabue',            flag: '🇿🇼', lang: 'en' },

  // ── Oceanía ──
  { code: 'AU', name: 'Australia',           flag: '🇦🇺', lang: 'en' },
  { code: 'FJ', name: 'Fiyi',                flag: '🇫🇯', lang: 'en' },
  { code: 'NZ', name: 'Nueva Zelanda',       flag: '🇳🇿', lang: 'en' },
  { code: 'PG', name: 'Papúa N. Guinea',     flag: '🇵🇬', lang: 'en' },
];

export const LANGUAGES = [
  { code: 'es', name: 'Español' },
  { code: 'en', name: 'English' },
  { code: 'pt', name: 'Português' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'ru', name: 'Русский' },
  { code: 'ja', name: '日本語' },
  { code: 'zh', name: '中文' },
  { code: 'ar', name: 'العربية' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'ko', name: '한국어' },
  { code: 'tr', name: 'Türkçe' },
];

export const countryByCode = (code) => COUNTRIES.find(c => c.code === code);
export const languageByCode = (code) => LANGUAGES.find(l => l.code === code);
